version: '3.8'

services:
  api:
    image: tototus/fastapi-app:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/monitoring/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
