"""Initial tables

Revision ID: 47914f72a522
Revises: 
Create Date: 2025-10-16 07:52:44.796250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47914f72a522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
